# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-09-26 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0005_auto_20161218_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputloggedrequest',
            name='slug',
            field=models.SlugField(blank=True, null=True, verbose_name='slug'),
        ),
        migrations.AddField(
            model_name='inputloggedrequest',
            name='url_pattern',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='URL pattern'),
        ),
    ]
