# Generated by Django 2.2.5 on 2019-09-19 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0013_auto_20190904_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandlog',
            name='output',
            field=models.TextField(blank=True, editable=False, null=True, verbose_name='output'),
        ),
    ]
